# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

env: {% if '1.11' in cookiecutter.django_versions %}
  - TOX_ENV=py36-django-111
  - TOX_ENV=py35-django-111
  - TOX_ENV=py34-django-111
  - TOX_ENV=py27-django-111{% endif %}{% if '2.0' in cookiecutter.django_versions %}
  - TOX_ENV=py36-django-20
  - TOX_ENV=py35-django-20
  - TOX_ENV=py34-django-20{% endif %}{% if 'master' in cookiecutter.django_versions %}
  - TOX_ENV=py34-django-master
  - TOX_ENV=py35-django-master
  - TOX_ENV=py36-django-master{% endif %}

matrix:
  fast_finish: true{% if 'master' in cookiecutter.django_versions %}
  allow_failures:
    - env: TOX_ENV=py34-django-master
    - env: TOX_ENV=py35-django-master
    - env: TOX_ENV=py36-django-master{% endif %}

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pipenv install --dev

# command to run tests using coverage, e.g. python setup.py test
script: pipenv run tox -e $TOX_ENV

after_success:
  - pipenv run codecov -e TOX_ENV
