# Config file for automatic testing at travis-ci.org

language: python

python:{% if '1.11' in cookiecutter.django_versions %}
  - "2.7"{% endif %}
  - "3.4"
  - "3.5"
  - "3.6"

env:{% if '1.11' in cookiecutter.django_versions %}
  - DJANGO=1.11{% endif %}{% if '2.0' in cookiecutter.django_versions %}
  - DJANGO=2.0{% endif %}{% if 'master' in cookiecutter.django_versions %}
  - DJANGO=master{% endif %}

matrix:{% if '2.0' in cookiecutter.django_versions %}
  exclude:
    - python: "2.7"
      env: DJANGO=2.0{% endif %}
  include:
    - python: "3.6"
      env: TOXENV=quality
    - python: "3.6"
      env: TOXENV=docs

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov
